# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssocreds < Formula
  desc "A tool to get temporary credentials from AWS SSO."
  homepage "https://github.com/winebarrel/ssocreds"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/ssocreds/releases/download/v0.1.0/ssocreds_0.1.0_darwin_amd64.tar.gz"
      sha256 "293e8abd58601d0a5c3b61e8bf65967bfa6938edf37fe58b41e7df469abf83f5"

      def install
        bin.install 'ssocreds'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/ssocreds/releases/download/v0.1.0/ssocreds_0.1.0_darwin_arm64.tar.gz"
      sha256 "b4aa34da594b3df66924492eeeadd9df38614f7de50785ea22bc15ea3da94bc7"

      def install
        bin.install 'ssocreds'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/ssocreds/releases/download/v0.1.0/ssocreds_0.1.0_linux_arm64.tar.gz"
      sha256 "7bec66effe3e3f4786d89b59ebf596d5fdc30727f0d7335ee2f0fed093951f1b"

      def install
        bin.install 'ssocreds'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/ssocreds/releases/download/v0.1.0/ssocreds_0.1.0_linux_amd64.tar.gz"
      sha256 "1ea9de0a6ac1ccc67bd4cd79ed38cf73fe36592523d134f832eeeddb78a5ece9"

      def install
        bin.install 'ssocreds'
      end
    end
  end
end
