# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssocreds < Formula
  desc "A tool to get temporary credentials from AWS SSO."
  homepage "https://github.com/winebarrel/ssocreds"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/ssocreds/releases/download/v0.2.1/ssocreds_0.2.1_darwin_amd64.tar.gz"
      sha256 "ccc60f05c04cac1652a4b88e646f9cdf978b4e3f072dffaca0d70d5d25cd4ae1"

      def install
        bin.install 'ssocreds'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/ssocreds/releases/download/v0.2.1/ssocreds_0.2.1_darwin_arm64.tar.gz"
      sha256 "938f92eeaa639492721eb8f67550ad783ca46fd81a5906f607c5371a46446c8a"

      def install
        bin.install 'ssocreds'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/ssocreds/releases/download/v0.2.1/ssocreds_0.2.1_linux_amd64.tar.gz"
      sha256 "09455631a83c555e54655fb7c2febda040ea52835a445430c4e0922d44dc2e36"

      def install
        bin.install 'ssocreds'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/ssocreds/releases/download/v0.2.1/ssocreds_0.2.1_linux_arm64.tar.gz"
      sha256 "c2e6de64e2794a4f015b3102d2d2aacb11ae6628ddff76326ff9222c493290ce"

      def install
        bin.install 'ssocreds'
      end
    end
  end
end
